language: ruby
bundler_args: --without development production
# before_script: ./bin/ci/before_build.sh
# script: "bundle exec rake spec:ci"
before_script: bundle exec rake db:migrate
script: bundle exec rspec spec
rvm:
  # - 1.8.7
  # - rbx-19mode
  # - jruby-19mode
  # - jruby-head
  # - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
  # - gemfiles/eventmachine-pre
notifications:
  recipients:
    - torsten.graf.oettel@gmail.com
branches:
  only:
    - master