# General options
mode: "textareas"
theme: "advanced"
skin: "bootstrap" # https://github.com/gtraxx/tinymce-skin-bootstrap

# Theme options
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1:
  - bold
  - italic
  - separator
  - underline
  - strikethrough
  - separator
  - bullist
  - numlist
  - separator
  - outdent
  - indent
  - separator
  - sub
  - sup
  - separator
theme_advanced_buttons2: 
theme_advanced_buttons3: 
# theme_advanced_statusbar_location: 
theme_advanced_resizing: true
content_css: "/assets/application.css"
