<% config = App.config %>

auth:
  key:      <%= config.transloadit.key! %>
  secret:   <%= config.transloadit.secret! %>
  duration: 1800
  # 30 minute validity period for signed upload forms

templates:
  # template defined inline
  upload:
    steps:
      thumbnail:
        robot:  /image/resize
        use:    ':original'
        width:    90
        height:   90
      fullsize:
        robot:  /image/resize
        use:    ':original'
        width:   640
        height: 1000
      export:
        use:
        - ':original'
        - fullsize
        - thumbnail
        robot: /s3/store
        key:    <%= config.transloadit.s3_key! %>
        secret: <%= config.transloadit.s3_secret! %>
        bucket: <%= config.transloadit.s3_bucket! %>
        path: ${assembly.id}/${previous_step.name}_${file.url_name}
