require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestsController do

  # This should return the minimal set of attributes required to create a valid
  # Quest. As you add validations to Quest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all quests as @quests" do
      quest = Quest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quests).should eq([quest])
    end
  end

  describe "GET show" do
    it "assigns the requested quest as @quest" do
      quest = Quest.create! valid_attributes
      get :show, {:id => quest.to_param}, valid_session
      assigns(:quest).should eq(quest)
    end
  end

  describe "GET new" do
    it "assigns a new quest as @quest" do
      get :new, {}, valid_session
      assigns(:quest).should be_a_new(Quest)
    end
  end

  describe "GET edit" do
    it "assigns the requested quest as @quest" do
      quest = Quest.create! valid_attributes
      get :edit, {:id => quest.to_param}, valid_session
      assigns(:quest).should eq(quest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Quest" do
        expect {
          post :create, {:quest => valid_attributes}, valid_session
        }.to change(Quest, :count).by(1)
      end

      it "assigns a newly created quest as @quest" do
        post :create, {:quest => valid_attributes}, valid_session
        assigns(:quest).should be_a(Quest)
        assigns(:quest).should be_persisted
      end

      it "redirects to the created quest" do
        post :create, {:quest => valid_attributes}, valid_session
        response.should redirect_to(Quest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quest as @quest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Quest.any_instance.stub(:save).and_return(false)
        post :create, {:quest => {}}, valid_session
        assigns(:quest).should be_a_new(Quest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Quest.any_instance.stub(:save).and_return(false)
        post :create, {:quest => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quest" do
        quest = Quest.create! valid_attributes
        # Assuming there are no other quests in the database, this
        # specifies that the Quest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Quest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => quest.to_param, :quest => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested quest as @quest" do
        quest = Quest.create! valid_attributes
        put :update, {:id => quest.to_param, :quest => valid_attributes}, valid_session
        assigns(:quest).should eq(quest)
      end

      it "redirects to the quest" do
        quest = Quest.create! valid_attributes
        put :update, {:id => quest.to_param, :quest => valid_attributes}, valid_session
        response.should redirect_to(quest)
      end
    end

    describe "with invalid params" do
      it "assigns the quest as @quest" do
        quest = Quest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Quest.any_instance.stub(:save).and_return(false)
        put :update, {:id => quest.to_param, :quest => {}}, valid_session
        assigns(:quest).should eq(quest)
      end

      it "re-renders the 'edit' template" do
        quest = Quest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Quest.any_instance.stub(:save).and_return(false)
        put :update, {:id => quest.to_param, :quest => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quest" do
      quest = Quest.create! valid_attributes
      expect {
        delete :destroy, {:id => quest.to_param}, valid_session
      }.to change(Quest, :count).by(-1)
    end

    it "redirects to the quests list" do
      quest = Quest.create! valid_attributes
      delete :destroy, {:id => quest.to_param}, valid_session
      response.should redirect_to(quests_url)
    end
  end

end
